### ISSUE TITLE
Not a pratical README file

### ISSUE THREAD

**Issue by cerdamejiaj** [Efruit/marqit#1]
Your README file can use some changes.  It should be clear if people need to pay to use this project or not.  Do not include any trolling installation instructions, looks very unprofessional. If anyone wanted to use this project they wouldn't feel safe about using it. I suggest making your README file more professional and user-friendly and update it if you still working on this project. I would like to see if you have made any changes to it. Thank you.

**Comment by Efruit** [comment]
Sorry about that. This repo has been unmaintained since late 2015, as I didn't have enough experience in the fields project was trying to emulate. As such, I wasn't able to make a realistic simulation environment. In retrospect, it would have been worthy of archival shortly after the last commit, but that feature didn't come around until November 2017.
